#!/bin/sh

NAME='djackets_django'
DJANGODIR=/webapps/djackets/djackets_django
SOCKFILE=/webapps/djackets/environment_3_8_10/run/gunicorn.sock
USER=djackets
GROUP=webapps
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=djackets_django.settingsprod
DJANGO_WSGI_MODULE=djackets_django.wsgi
TIMEOUT=120

cd $DJANGODIR
source ../environment_3_8_10/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec ../environment_3_8_10/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--timeout $TIMEOUT \
--user=$USER --group=$GROUP \
--bind=0.0.0.0:8000 \  #port 방식임
#--bind=unix:$SOCKFILE \  #socket 방식으로 확인이 필요하다 test 를 위해 port 방식으로 진행하였다.
--log-level=debug \
--log-file=-